Testing new publisher script approach.

diff --git a/.github/workflows/publish-snapshot.yml b/.github/workflows/publish-snapshot.yml
--- a/.github/workflows/publish-snapshot.yml
+++ b/.github/workflows/publish-snapshot.yml
@@ -5,71 +5,109 @@ on:
 env:
   GRADLE_JAVA_VERSION: 20
   JAVA_VERSION: 21
-  GRADLE_VERSION: 8.3
+  GRADLE_VERSION: 8.4
   PROJECT_NAME: glib
+  VERSION_FILE_PATH: ${{ github.workspace }}/version
 jobs:
-  all-in-one:
-    permissions:
-      packages: write # Packages.
-      id-token: write # Pages.
-      pages: write    # Pages.
+  sanity_check:
     runs-on: ubuntu-latest
+    outputs:
+      version: ${{ steps.version.outputs.version }}
+
     steps:
       - name: Checkout
-        uses: actions/checkout@v3
-        with:
-          ref: dev
+        uses: actions/checkout@v4
+        # with:
+        #   ref: dev
+
+      - name: Get version
+        id: version
+        run: |
+          version="v$(head -n 1 ${{ env.VERSION_FILE_PATH }})"
+          echo "version=${version}" >> "$GITHUB_OUTPUT"
 
       - name: Snapshot test
         working-directory: code
         run: |
-          version=$(<"${{ env.PROJECT_NAME }}/src/main/resources/version")
-          if [[ "${version}" != *"-SNAPSHOT" ]]; then
-            echo "'dev' only releases snapshots!"
+          echo "v: ${{ steps.version.outputs.version }}"
+          echo "branch: ${{ github.ref_name }}"
+          if [[ "${{ github.ref_name }}" != "dev" ]]; then
+            echo "Snapshots are only allowed on dev branch!"
+            exit 1
+          fi
+          if [[ "${{ steps.version.outputs.version }}" != *"-SNAPSHOT" ]]; then
+            echo "Only snapshots are allowed on dev branch!"
             exit 1
           fi
 
-      - name: Setup Java for Gradle
-        uses: oracle-actions/setup-java@v1
-        with:
-          release: ${{ env.GRADLE_JAVA_VERSION }}
+  # snapshot_package:
+  #   permissions:
+  #     packages: write # Packages.
+  #     id-token: write # Pages.
+  #     pages: write    # Pages.
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #       with:
+  #         ref: dev
 
-      - name: Setup Java
-        uses: oracle-actions/setup-java@v1
-        with:
-          release: ${{ env.JAVA_VERSION }}
+  #     - name: Get version
+  #       id: version
+  #       run: |
+  #         version="v$(head -n 1 ${{ env.VERSION_FILE_PATH }})"
+  #         echo "version=${version}" >> "$GITHUB_OUTPUT"
 
-      - name: Setup Gradle
-        uses: gradle/gradle-build-action@v2
-        with:
-          gradle-version: ${{ env.GRADLE_VERSION }}
+  #     - name: Snapshot test
+  #       working-directory: code
+  #       run: |
+  #         echo "v: ${{ steps.version.outputs.version }}"
+  #         if [[ "${{ steps.version.outputs.version }}" != *"-SNAPSHOT" ]]; then
+  #           echo "'dev' ONLY releases snapshots!"
+  #           exit 1
+  #         fi
 
-      - name: Test
-        working-directory: code
-        run: gradle :${{ env.PROJECT_NAME }}:test
+  #     - name: Setup Java for Gradle
+  #       uses: oracle-actions/setup-java@v1
+  #       with:
+  #         release: ${{ env.GRADLE_JAVA_VERSION }}
 
-      - name: Build
-        working-directory: code
-        run: gradle :${{ env.PROJECT_NAME }}:build
+  #     - name: Setup Java
+  #       uses: oracle-actions/setup-java@v1
+  #       with:
+  #         release: ${{ env.JAVA_VERSION }}
 
-      - name: Recreate GPG keys
-        run: echo "${{ secrets.GPG_KEYS_BASE64 }}" | base64 -d > "${{ github.workspace }}/gpg-keys"
+  #     - name: Setup Gradle
+  #       uses: gradle/gradle-build-action@v2
+  #       with:
+  #         gradle-version: ${{ env.GRADLE_VERSION }}
 
-      - name: Publish
-        working-directory: code
-        run: |
-          gradle \
-            "-Pgpr.username=${{ github.actor }}" \
-            "-Pgpr.token=${{ secrets.GITHUB_TOKEN }}" \
-            "-Psigning.keyId=${{ secrets.GPG_KEY_ID }}" \
-            "-Psigning.password=${{ secrets.GPG_PASSWORD }}" \
-            "-Psigning.secretKeyRingFile=${{ github.workspace }}/gpg-keys" \
-            :${{ env.PROJECT_NAME }}:publish
+  #     - name: Test
+  #       working-directory: code
+  #       run: gradle :${{ env.PROJECT_NAME }}:test
 
-      - name: Clean up old snapshots
-        uses: actions/delete-package-versions@v4
-        with:
-          package-name: com.glitchybyte.glib.glib
-          package-type: maven
-          min-versions-to-keep: 1
-          delete-only-pre-release-versions: "true"
+  #     - name: Build
+  #       working-directory: code
+  #       run: gradle :${{ env.PROJECT_NAME }}:build
+
+  #     - name: Recreate GPG keys
+  #       run: echo "${{ secrets.GPG_KEYS_BASE64 }}" | base64 -d > "${{ github.workspace }}/gpg-keys"
+
+  #     - name: Publish
+  #       working-directory: code
+  #       run: |
+  #         gradle \
+  #           "-Pgpr.username=${{ github.actor }}" \
+  #           "-Pgpr.token=${{ secrets.GITHUB_TOKEN }}" \
+  #           "-Psigning.keyId=${{ secrets.GPG_KEY_ID }}" \
+  #           "-Psigning.password=${{ secrets.GPG_PASSWORD }}" \
+  #           "-Psigning.secretKeyRingFile=${{ github.workspace }}/gpg-keys" \
+  #           :${{ env.PROJECT_NAME }}:publish
+
+  #     - name: Clean up old snapshots
+  #       uses: actions/delete-package-versions@v4
+  #       with:
+  #         package-name: com.glitchybyte.glib.glib
+  #         package-type: maven
+  #         min-versions-to-keep: 1
+  #         delete-only-pre-release-versions: "true"
